### ISSUE TITLE
Had to edit models

### ISSUE THREAD

**Issue by DB-009** [lexxyungcarter/laravel-5-messenger#1]
I had to edit the models to get it to work for me correctly I was wondering how can I move the files into my proect without requiring it as a vendor so i can make more modifications? if possible im wanting to fork it and extend it to be more modular

**Comment by syntaxlexx** [comment]
In my view, it would be fairly simpler to continue maintaining it and using it as a package in your project. If you have already edited files in your workspace, I think it's better forking this project and replacing the individual edited files inside the forked project, add a version number, and submit your repo to packagist. Form there you can simply 'require' it in your composer. 

Any modifications done on the local repo will only reflect in your new (forked) package.

**Comment by syntaxlexx** [comment]
If you don't need to require it as a vendor package, you can simply copy the models to your models folder, and the trait. Keep track of the namespaces.
