### ISSUE TITLE
Starred property

### ISSUE THREAD

**Issue by snarcraft** [lexxyungcarter/laravel-5-messenger#10]
So when a participant "stars" a thread, all the others will see that thread as starred?
Is it what you are expecting?
Perhaps the starred property could be in the participant table so that each participant will see his own starred threads.
I think this makes more sense

**Comment by syntaxlexx** [comment]
@snarcraft that actually makes absolute sense. Changes will reflect in the next upcoming release.

**Comment by syntaxlexx** [comment]
@snarcraft ,
The starred property has been updated accordingly. You can update to latest release or check the updated examples/readme files.
