### ISSUE TITLE
I can use two user's table?

### ISSUE THREAD

**Issue by bebetoalves** [lexxyungcarter/laravel-5-messenger#12]
I wonder if it is possible to use two distinct tables of users.

**Comment by syntaxlexx** [comment]
@bebetoalves not currently.

The participants table has only one `user_id` column. If you wish to use two tables, you can create a migration to add a column for the other model. You should then proceed to define relationships of threads and your other model. That would introduce some complexity in your code, but if it is worth it, go for it. :-)
