### ISSUE TITLE
Integrate Pusher on Laravel 5.6

### ISSUE THREAD

**Issue by impactcolor** [lexxyungcarter/laravel-5-messenger#15]
How would I integrate Pusher on Laravel 5.6?  The docs are a little confusing on pusher.  
I uncommented broadcast in config app and installed package.  Everything works great but I don't see any data on the pusher dashboard.

**Comment by syntaxlexx** [comment]
Hi @impactcolor ,
kindly check out the examples to get it working.

Essentially, the new laravel-ish way of accomplishing that would be via firing an event and registering channels. The examples and the demo offer a good place to view it. 
Also, broadcasting should not be commented out.  (The laravel docs are pretty straight forward ~ at least to me)

For more enquiries, I'll be here.
