### ISSUE TITLE
extend message model to everride it's fillable

### ISSUE THREAD

**Issue by mooahmad** [lexxyungcarter/laravel-5-messenger#17]
hi ,
i want to override the fillables to add new attributes

**Comment by syntaxlexx** [comment]
Hi @mooahmad ,

How about creating your own `App/Message` model and extending it to the base `Message` class?
Something like:
```php

use Lexx\ChatMessenger\Models\Message as BaseModel;

class Message extends BaseModel
{
         $fillable = [];
}
```
Let me know how that goes.
