### ISSUE TITLE
how to create group chat using this package

### ISSUE THREAD

**Issue by RJonwal** [lexxyungcarter/laravel-5-messenger#22]
Hello ,  thank you for awesome package
i'm using this package for chat messenger  , private chat is working fine 
now i have to create group chat, where i user can create group , group messaging, add & remove users from group  

here , not so much described about group messaging

please help me

**Comment by syntaxlexx** [comment]
Hi there,

To simulate a group messaging, it would be as simple as adding new users to the thread. The thread can also be set to limit participants(users) to a certain limit (e.g. 255 like whatsapp).
The thread can also have its own link which when shared, a user can be joined to the thread.
