### ISSUE TITLE
No realtime updates conversation?

### ISSUE THREAD

**Issue by Swiek** [lexxyungcarter/laravel-5-messenger#3]
Hi,

I was testing your package. Is is correct that you only get a notification that there is a new messages and that the conversation isn't updated, so you have a realtime chat?

Kind regards,

Erwin

**Comment by syntaxlexx** [comment]
Hello,

kindly post some piece of your code for more assistance. 
As a reminder, I hope you have uncommented this line in **config/app.php**
```php
        App\Providers\BroadcastServiceProvider::class,
```
as it is usually commented by default (and actually ascertaining that pusher itself receives a broadcast message from the client)

**Comment by Swiek** [comment]
Hi Lexx, 

I found out that you build it so you get a notification. I found a tutorial to change it so it will update the screen of the other user so he see the messages the other person send.

Erwin

**Comment by impactcolor** [comment]
@Doublemedia Can you please reference the tutorial?
