### ISSUE TITLE
removeParticipant()

### ISSUE THREAD

**Issue by bhdrnzl** [lexxyungcarter/laravel-5-messenger#4]
Hello there. Even if the user leaves the chat, the new user will be notified when the new message is written. How do I get past that?

**Comment by syntaxlexx** [comment]
Hello there,

Would you post a snippet of your code to illustrate this? Thank you.

**Comment by bhdrnzl** [comment]
```
public function leave($id)
    {
        $thread = Thread::find($id);
        $thread->removeParticipant(Auth::id());
        if ($thread) {

            toastr()->success('You left the conversation');

            return back();

        } else {

            toastr()->error('You cant leave conversation');

            return back();
        }
    }
```

**Comment by bhdrnzl** [comment]
@lexxyungcarter Is there a clue about this error?

**Comment by syntaxlexx** [comment]
Hi @bhdrnzl ,
Let me set up a simple demo to replicate the issue.

**Comment by syntaxlexx** [comment]
Hello @bhdrnzl ,
When sending the message, could you be calling 
```php
$thread->activateAllParticipants();
```

Because if you do so, all previously removed participants will be included back to the conversation. try commenting the piece of code and see the results.

I have set up a simple demo app [over here](https://github.com/lexxyungcarter/laravel-5-messenger-demo). 
The complete working demo is [demonstrated here](https://messenger.acelords.space).

Also, make sure to update to the latest version of the package (version 1.0.7). It includes some important updates.

**Comment by bhdrnzl** [comment]
Hi @lexxyungcarter,
Thank you for working. I copied the MessagesController.php file in your example and added it to my own project. The notification continues to go to the user leaving the chat.

**Comment by syntaxlexx** [comment]
Ok. If that is the case, you can simply comment that line in the `update()` method
```php
// comment or remove this to avoid activating all participants 
// (including those who have been removed from a thread conversation
$thread->activateAllParticipants();
```

and then test your app.

**Comment by bhdrnzl** [comment]
Hi @lexxyungcarter ..
I guess I couldn't tell you what the problem was. When a user leaves the chat, the other people continue to chat and the user continues to send new message notifications. The message does not appear because the user has left the chat, but the notification icon is lit.

With this code, the user leaves the conversation.
`

    public function leave($id)
    {
        $thread = Thread::find($id);
        $thread->removeParticipant(Auth::id());

        if ($thread) {

            toastr()->success('Ok..');

            return back();
        } else {

            toastr()->error('No..');

            return back();
        }
    }`

I can see in the database that I left talking, but the notification continues to go.
PhpMyadmin screenshot: [https://ibb.co/RhXFKS5](https://ibb.co/RhXFKS5)

i removed this code:
`$thread->activateAllParticipants();`

still notifications are coming..

**Comment by syntaxlexx** [comment]
Hi @bhdrnzl ,

An update has been released and you can update to the latest release.

Cheers.

**Comment by bhdrnzl** [comment]
Cheers, sir. I am grateful to you for preparing such a package because I use it in all my projects. And thank you for paying attention to the problem.

**Comment by syntaxlexx** [comment]
@bhdrnzl It's always a pleasure helping others out.
Cheers!
