### ISSUE TITLE
user column name

### ISSUE THREAD

**Issue by bhdrnzl** [lexxyungcarter/laravel-5-messenger#5]
Hi Lex,

I renamed the name column in the Users table to nick. The problem was solved when I updated the thread.php file from the localhostta vendors / lex group, but I can't make the necessary changes to the vendors folder because I have uplkoad with laravel forge. And so I get the name column not found error. How can I solve this problem?

**Comment by syntaxlexx** [comment]
Hi @bhdrnzl ,

As for your specific change, you can try declaring an **Accessor** inside your `users` model.
Place the following method inside your User's model.

```php
// User.php - the user model


// assuming you changed the 'name' column to be 'username'.
public function getNameAttribute()
{
    return $this->username;
}

```

**Comment by bhdrnzl** [comment]
Thanx Lexx...
