### ISSUE TITLE
Laravel 5.8 supprt?

### ISSUE THREAD

**Issue by tobz-nz** [lexxyungcarter/laravel-5-messenger#6]

**Comment by syntaxlexx** [comment]
We are currently testing out Laravel 5.8 support, and will unleash any updates within the week.

With the updates comes also updating the demo website to Laravel 5.8.

Cheers.

**Comment by syntaxlexx** [comment]
Hi @tobz-nz ,

We are glad to inform you of the new release. With this release comes support for Laravel 5.8.

The demo project source code has also been updated to reflect the same.

Cheers.

**Comment by syntaxlexx** [comment]
... Just as a follow-up, package now supports Laravel 6. The examples/readme have been updated accordingly also.

Cheers!
