### ISSUE TITLE
Thread::participantsString() fail with custom User table

### ISSUE THREAD

**Issue by nightgryphon** [lexxyungcarter/laravel-5-messenger#7]
The participantsString() method query users table directly without respect to user model. I use Sentinel/Sentry for auth and users table does not have 'name' column so participantsString() fails. On the other hand my User model have getter for 'name' property so the participantsString() can get user names if work with the proper User model.

**Comment by syntaxlexx** [comment]
Hi @nightgryphon ,

Please refer here

https://github.com/lexxyungcarter/laravel-5-messenger/issues/5#issuecomment-463389955

**Comment by syntaxlexx** [comment]
Hi @nightgryphon ,
As an addition, you can specify the columns to pass onto `participantsString()` as the second parameter.

```blade
    <p>
        <small><strong>Participants:</strong> {{ $thread->participantsString(Auth::id(), ['username']) }}</small>
    </p>
```

**Comment by nightgryphon** [comment]
I've declared the accessor for name attribute and it work fine for other functions i use. But for this one it does not work because it does not use the user model

**Comment by nightgryphon** [comment]
Also i use first_name and last_name so there is no single column to choose.

**Comment by syntaxlexx** [comment]
try
```php
$thread->participantsString(Auth::id(), ['first_name', 'last_name'])
```
provided the `first_name` and `last_name` columns are in the `users` table. 

If your setup is similar to the examples given, the file is located in 
`view('messenger.partials.thread')`
