### ISSUE TITLE
One Thread by user (Like Facebook Messenger system)

### ISSUE THREAD

**Issue by CyrilBlankaert** [lexxyungcarter/laravel-5-messenger#9]
Hello, and thanks for this awesome package ! 

I would like to create a messenger application where the Authentified user can only create one thread by user (like Messenger) 

For example, If a discussion between user_1 and user_2 exist, user_2 is not listed in the create thread page. 

How can I do this ? 
Thank you ! :)

**Comment by syntaxlexx** [comment]
Hi @CyrilBlankaert ,

For that custom functionality, I think you'll have to loop over the threads and check if among the participants there exists one where the user exists. If one exists, then retrieve the thread and compose a message in it (instead of creating a new thread).
